# Generated by Django 4.1.1 on 2022-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newloginapp', '0002_alter_marksheet_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
