# Generated by Django 4.1.1 on 2022-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newloginapp', '0003_marksheet_created_at_marksheet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='updated_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
